version: "3.9"

services:
  
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  rails:
    image: ghcr.io/j4nn1k/project-portfolio:latest
    # build: .
    command: bundle exec rails server -b 0.0.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  nginx:
    image: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rails

volumes:
  postgres: